name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.11.1, 12.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo "github.ref = ${{ github.ref }}"
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn test:ci

  build_docker_images:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Capture Tag Name
        id: tag_name
        run: echo ::set-output name=GIT_TAG::${GITHUB_REF#refs/tags/}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build App Image
        run: |
          cd docker
          docker-compose build

      - name: Push App Images
        run: |
          docker tag ucfopen/obojobo:app-dev ghcr.io/${{ github.repository_owner }}/obojobo:app-${{ github.sha }}
          docker tag ucfopen/obojobo:app-dev ghcr.io/${{ github.repository_owner }}/obojobo:app-${{ steps.tag_name.outputs.GIT_TAG }}
          docker tag ucfopen/obojobo:nginx-dev ghcr.io/${{ github.repository_owner }}/obojobo:nginx-${{ github.sha }}
          docker tag ucfopen/obojobo:nginx-dev ghcr.io/${{ github.repository_owner }}/obojobo:nginx-${{ steps.tag_name.outputs.GIT_TAG }}
